### ISSUE TITLE
Socket is created, but can not get connection confirm from ('localhost', 9000), timeout after 1.00 seconds

### ISSUE THREAD

**Issue by louEugene** [unrealcv/unrealcv#80] opened 2017-07-26 08:39 UTC
Typed this code
```
from unrealcv import client
client.connect()

```
got error

> ERROR:__init__:161:Socket is created, but can not get connection confirm from ('localhost', 9000), timeout after 1.00 seconds
ERROR:__init__:223:Fail to send message, client is not connected
ERROR:__init__:317:Can not receive a response from server, timeout after 5.00 seconds

Anyone konw why?
using UE4.15, unrealcv 0.39

**Comment by zfw1226** [comment] 2017-07-26 08:56
Maybe you need to check your UnrealCV server IP and port, typing this command in the game console: 
```
vget /unrealcv/status
```

**Comment by zfw1226** [comment] 2017-07-26 09:14
Sorry, I closed this issue by mistake.
Maybe you need to check the IP and port of UnrealCV server, typing this command in the game console:
```
vget /unrealcv/status
```
Sometimes, this issue is caused by the port confliction.  
You can change the port ID in ``unrealcv.init``. And then, you can run the client like this:
```
import unrealcv
client = unrealcv.Client(('127.0.0.1', 9001))# '127.0.0.1' is the server IP address, 9001 is the server port ID, please change it to align to your UnrealCV server.
client.connect()
``` 
Besides，where do you run the UE game, in UEeditor or in Binary?

**Comment by louEugene** [comment] 2017-07-26 10:03
I'm using UEeditor, I check the status, and it gives me this:
![image 1](https://user-images.githubusercontent.com/19661784/28615402-7c1fb3c0-722b-11e7-82a9-4ec723b61a80.png)
I'm not sure if it's correct since I can't see Server IP, only Port ID is available.

**Comment by zfw1226** [comment] 2017-07-26 10:16
Well, the default IP is ``'127.0.0.1'``. Your port ID is ``9001``, but the default IP of UnrealCV Client is ``9000``.
So you can copy the example client code that I referred in the last reply to configure the port ID in the client to connect the UnrealCV server.

**Comment by louEugene** [comment] 2017-07-26 10:17
@zfw1226 Thanks so much, It works now.

**Comment by zfw1226** [comment] 2017-10-04 04:54
@abhay-venkatesh I am not sure that what is wrong with you. The RealisticRendering binary works well when I test it in Windows and Linux. I run the command in console and get response like this.
![console](https://user-images.githubusercontent.com/12609475/31160407-babc86ae-a902-11e7-8840-4ac06171becf.JPG)

**Closed** 2017-12-12 13:02 UTC
