### ISSUE TITLE
error when install unrealcv-0.3.9

### ISSUE THREAD

**Issue by YingXiuHe** [unrealcv/unrealcv#87] opened 2017-09-10 02:32 UTC
My operating system is Ubuntu 16.04 , UnrealEngine4, unrealcv-0.3.9. when i run the build.sh, i face a problem , the error codes as fllows 
`UnrealBuildTool:   Running UnrealHeaderTool "/home/gnss/hxy/unrealcv-0.3.9/Plugins/UnrealCV/HostProject/HostProject.uproject" "/home/gnss/hxy/unrealcv-0.3.9/Plugins/UnrealCV/HostProject/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
UnrealBuildTool: Refusing to run with the root privileges.
UnrealBuildTool: Error: UnrealHeaderTool failed for target 'UE4Editor' (platform: Linux, module info: /home/gnss/hxy/unrealcv-0.3.9/Plugins/UnrealCV/HostProject/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UE4Editor.uhtmanifest, exit code: Canceled (1)).
CommandUtils.Run: Run: Took 9.504526s to run mono, ExitCode=1
Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:1): /home/gnss/hxy/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe UE4Editor Linux Development -project="/home/gnss/hxy/unrealcv-0.3.9/Plugins/UnrealCV/HostProject/HostProject.uproject"  -module UnrealCV -receipt /home/gnss/hxy/unrealcv-0.3.9/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Binaries/Linux/UE4Editor.target -NoHotReload. See logfile for details: 'UnrealBuildTool-2017.09.10-09.47.56.txt' 
  at AutomationTool.CommandUtils.RunAndLog (System.String App, System.String CommandLine, System.String Logfile, Int32 MaxSuccessCode, System.String Input, ERunOptions Options, System.Collections.Generic.Dictionary`2 EnvVars, AutomationTool.SpewFilterCallbackType SpewFilterCallback) <0x41383000 + 0x002f7> in <filename unknown>:0 
  at AutomationTool.CommandUtils.RunAndLog (AutomationTool.CommandEnvironment Env, System.String App, System.String CommandLine, System.String LogName, Int32 MaxSuccessCode, System.String Input, ERunOptions Options, System.Collections.Generic.Dictionary`2 EnvVars, AutomationTool.SpewFilterCallbackType SpewFilterCallback) <0x41382cf0 + 0x00057> in <filename unknown>:0 
  at AutomationTool.CommandUtils.RunUBT (AutomationTool.CommandEnvironment Env, System.String UBTExecutable, System.String CommandLine, System.String LogName, System.Collections.Generic.Dictionary`2 EnvVars) <0x41382b10 + 0x0015f> in <filename unknown>:0 
  at BuildPlugin.CompilePluginWithUBT (UnrealBuildTool.FileReference HostProjectFile, UnrealBuildTool.FileReference HostProjectPluginFile, UnrealBuildTool.PluginDescriptor Plugin, System.String TargetName, TargetType TargetType, UnrealTargetPlatform Platform, UnrealTargetConfiguration Configuration, System.Collections.Generic.List`1 ReceiptFileNames, System.String InAdditionalArgs) <0x41381680 + 0x00573> in <filename unknown>:0 
  at BuildPlugin.CompilePlugin (UnrealBuildTool.FileReference HostProjectFile, UnrealBuildTool.FileReference HostProjectPluginFile, UnrealBuildTool.PluginDescriptor Plugin, System.Collections.Generic.List`1 HostPlatforms, System.Collections.Generic.List`1 TargetPlatforms, System.String AdditionalArgs) <0x41380a20 + 0x00237> in <filename unknown>:0 
  at BuildPlugin.ExecuteBuild () <0x41371b00 + 0x005d3> in <filename unknown>:0 
  at AutomationTool.BuildCommand.Execute () <0x41371ae0 + 0x00010> in <filename unknown>:0 
  at AutomationTool.Automation.Execute (System.Collections.Generic.List`1 CommandsToExecute, Tools.DotNETCommon.CaselessDictionary.CaselessDictionary`1 Commands) <0x41371680 + 0x0019f> in <filename unknown>:0 
  at AutomationTool.Automation.Process (System.String[] Arguments) <0x4131f000 + 0x00983> in <filename unknown>:0 
  at AutomationTool.Program.MainProc (System.Object Param) <0x4131e700 + 0x0005b> in <filename unknown>:0 
  at AutomationTool.InternalUtils.RunSingleInstance (System.Func`2 Main, System.Object Param) <0x4131e140 + 0x00299> in <filename unknown>:0 
  at AutomationTool.Program.Main () <0x412dffa0 + 0x00507> in <filename unknown>:0 
`
who can help me , i need help, and thank you very much.

**Comment by qiuwch** [comment] 2017-09-10 02:34
I saw  "WarningsAsErrors UnrealBuildTool: Refusing to run with the root privileges.". Did you run the command with sudo or under root account?

**Comment by YingXiuHe** [comment] 2017-09-10 02:39
yes , i noticed this line before ,but it can not solve my problem . and if i m not run the command with root , there will show ‘Permission denied’

**Comment by qiuwch** [comment] 2017-09-10 02:41
Permission denied is usually caused by not setting the file permission properly. 
To solve the "permission denied" issue, the correct way is using "chown" command to make files belong to your account, instead of root. And make sure the owner has write permission.

**Comment by YingXiuHe** [comment] 2017-09-10 02:50
ok , i m try to do it just now , and build it success.  thank you .

**Comment by qiuwch** [comment] 2017-09-10 02:51
No problem. I will close this one. If you have other problems, please open a new issue.

**Comment by YingXiuHe** [comment] 2017-09-10 02:52
ok.

**Closed** 2017-09-10 02:51 UTC
